export const styles = {
  mainMenu: {
    position: 'fixed',
    width: 'fit-content',
    height: '100vh',
    padding: 8,
    borderRadius: 10,
    boxShadow: '5px 1px 10px 1px #ccc',
  },
  menuList: { width: '100%' },
  menuItem: {
    listStyle: 'none',
    display: 'flex',
    alignItems: 'center',
    marginTop: 8,
    cursor: 'pointer',
  },
  menuDetail: { marginLeft: 12 },
  bodyContainer: { marginLeft: 200 },
  optionalMenu: {
    transitionDuration: '200ms',
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    border: '1px solid #ccc',
    height: '100vh',
    width: 320,
    position: 'fixed',
    right: 0,
    backgroundColor: 'white',
    zIndex: 1,
    boxShadow: '-5px 1px 10px 1px #ccc',
    paddingTop: 24,
    paddingLeft: 18,
    paddingRight: 18,
    paddingBottom: 24,
  },
  appContainer: { width: '100vw' },
  subAppContainer: { display: 'flex' },
};
